/*
 * Copyright 2025 The Carpocratian Church of Commonality and Equality, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * WasmBridge: TypeScript ↔ Rust/WASM integration layer
 *
 * This module provides:
 * - Lazy loading of the WASM module
 * - Type-safe wrappers around Rust types
 * - Graceful fallback if WASM fails to load
 * - Performance monitoring and logging
 */

import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// Import actual WASM types
// These are generated by wasm-bindgen and will be available after building
import type {
  Chronicle as WasmChronicle,
  Stack as WasmStack,
  Space as WasmSpace,
  Source as WasmSource,
  Token as WasmToken,
  ActionDispatcher as WasmActionDispatcher
} from '../core-rs/pkg/nodejs/hypertoken_core.js';

// Re-export WASM types for convenience
export type {
  WasmChronicle,
  WasmStack,
  WasmSpace,
  WasmSource,
  WasmToken,
  WasmActionDispatcher
};

/**
 * The actual type definitions come from the WASM module imports above.
 * The WASM module is generated by wasm-bindgen from Rust code.
 */

export interface HyperTokenWasm {
  Chronicle: new () => WasmChronicle;
  Stack: new () => WasmStack;
  Space: new () => WasmSpace;
  Source: new () => WasmSource;
  Token: new () => WasmToken;
  ActionDispatcher: new () => WasmActionDispatcher;
  version(): string;
  health_check(): boolean;
}

/**
 * WASM module state
 */
let wasmModule: HyperTokenWasm | null = null;
let wasmLoadPromise: Promise<HyperTokenWasm> | null = null;
let wasmLoadError: Error | null = null;

/**
 * Load the WASM module (cached, only loads once)
 *
 * @returns Promise that resolves to the WASM module
 * @throws Error if WASM fails to load
 */
export async function loadWasm(): Promise<HyperTokenWasm> {
  // Return cached module if already loaded
  if (wasmModule) {
    return wasmModule;
  }

  // Return existing load promise if already loading
  if (wasmLoadPromise) {
    return wasmLoadPromise;
  }

  // If previously failed, throw the cached error
  if (wasmLoadError) {
    throw wasmLoadError;
  }

  // Start loading
  wasmLoadPromise = (async () => {
    try {
      // Detect environment and load appropriate WASM package
      const __filename = fileURLToPath(import.meta.url);
      const __dirname = dirname(__filename);

      // Try to load the WASM module from the nodejs build
      const wasmPath = join(__dirname, '..', 'core-rs', 'pkg', 'nodejs', 'hypertoken_core.js');

      const wasmImport = await import(wasmPath);

      // Initialize WASM (wasm-bindgen generates an init function)
      if (wasmImport.default && typeof wasmImport.default === 'function') {
        await wasmImport.default();
      }

      // Cache the module
      wasmModule = wasmImport as HyperTokenWasm;

      console.log(`✅ HyperToken WASM loaded successfully (v${wasmModule.version()})`);

      return wasmModule;
    } catch (error) {
      wasmLoadError = error instanceof Error ? error : new Error(String(error));
      console.warn('⚠️  Failed to load WASM module:', wasmLoadError.message);
      console.warn('    Falling back to TypeScript implementation');
      throw wasmLoadError;
    }
  })();

  return wasmLoadPromise;
}

/**
 * Check if WASM is available (non-throwing)
 *
 * @returns true if WASM loaded successfully
 */
export function isWasmAvailable(): boolean {
  return wasmModule !== null;
}

/**
 * Get WASM module if loaded, otherwise return null
 *
 * @returns WASM module or null
 */
export function getWasmModule(): HyperTokenWasm | null {
  return wasmModule;
}

/**
 * Try to load WASM, but don't throw if it fails
 *
 * @returns Promise that resolves to WASM module or null
 */
export async function tryLoadWasm(): Promise<HyperTokenWasm | null> {
  try {
    return await loadWasm();
  } catch {
    return null;
  }
}

/**
 * Reset WASM module state (mainly for testing)
 */
export function resetWasm(): void {
  wasmModule = null;
  wasmLoadPromise = null;
  wasmLoadError = null;
}
